### PR TITLE
Feature/html assets folder

### PR DESCRIPTION
**Pull request by JonathanAbbema**
Adding HTML to main

### CODE REVIEW

**Comment by kristinaama** [comment]
approved

**Review by otmorales23 — APPROVED** [review]
approved hurrah!

**Review by Yeletta — APPROVED** [review]
Approved

**Review by RhettSimo — APPROVED** [review]
approved

**Review by Yeletta — APPROVED** [review]

**Review by kristinaama — APPROVED** [review]

**Pull request merged**
